ERROR - 2022-11-09 21:20:13 --> ErrorException: pg_query(): Query failed: ERROR:  relation "tbl_objek" already exists in C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140, Array)
#1 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Postgre\Connection.php(140): pg_query(Resource id #261, 'CREATE TABLE "t...')
#2 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "t...')
#3 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "t...')
#4 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Forge.php(509): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "t...')
#5 C:\xampp\htdocs\pgwl\petalokasiobjek\app\Database\Migrations\2022-09-29-013450_CreateTableObjek.php(51): CodeIgniter\Database\Forge->createTable('tbl_objek')
#6 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\MigrationRunner.php(868): App\Database\Migrations\CreateTableObjek->up()
#7 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\MigrationRunner.php(187): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(897): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#13 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\pgwl\petalokasiobjek\spark(98): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-11-09 21:22:23 --> ErrorException: pg_query(): Query failed: ERROR:  relation "tbl_objek" already exists in C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140, Array)
#1 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Postgre\Connection.php(140): pg_query(Resource id #261, 'CREATE TABLE "t...')
#2 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "t...')
#3 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "t...')
#4 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Forge.php(509): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "t...')
#5 C:\xampp\htdocs\pgwl\petalokasiobjek\app\Database\Migrations\2022-09-29-013450_CreateTableObjek.php(51): CodeIgniter\Database\Forge->createTable('tbl_objek')
#6 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\MigrationRunner.php(868): App\Database\Migrations\CreateTableObjek->up()
#7 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\MigrationRunner.php(187): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(897): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#13 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\pgwl\petalokasiobjek\spark(98): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-11-09 21:25:20 --> ErrorException: pg_query(): Query failed: ERROR:  relation "tbl_objek" already exists in C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140, Array)
#1 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Postgre\Connection.php(140): pg_query(Resource id #261, 'CREATE TABLE "t...')
#2 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "t...')
#3 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "t...')
#4 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Forge.php(509): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "t...')
#5 C:\xampp\htdocs\pgwl\petalokasiobjek\app\Database\Migrations\2022-09-29-013450_CreateTableObjek.php(51): CodeIgniter\Database\Forge->createTable('tbl_objek')
#6 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\MigrationRunner.php(868): App\Database\Migrations\CreateTableObjek->up()
#7 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\MigrationRunner.php(187): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(897): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#13 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\pgwl\petalokasiobjek\spark(98): CodeIgniter\CLI\Console->run()
#17 {main}
ERROR - 2022-11-09 21:37:34 --> ErrorException: pg_query(): Query failed: ERROR:  relation "tbl_objek" already exists in C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140, Array)
#1 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Postgre\Connection.php(140): pg_query(Resource id #261, 'CREATE TABLE "t...')
#2 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\BaseConnection.php(693): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "t...')
#3 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "t...')
#4 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\Forge.php(509): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "t...')
#5 C:\xampp\htdocs\pgwl\petalokasiobjek\app\Database\Migrations\2022-09-29-013450_CreateTableObjek.php(51): CodeIgniter\Database\Forge->createTable('tbl_objek')
#6 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\MigrationRunner.php(868): App\Database\Migrations\CreateTableObjek->up()
#7 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Database\MigrationRunner.php(187): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\pgwl\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#12 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(897): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#13 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#14 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\pgwl\petalokasiobjek\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\pgwl\petalokasiobjek\spark(98): CodeIgniter\CLI\Console->run()
#17 {main}
